# Edge Tech Laser Ablation Propulsion Module
# Purpose: Calculate thrust generated by laser-activated surface ablation.

def calculate_ablation_thrust(laser_power_kw, spot_size_mm2, pulse_duration_ns):
    # Ablation efficiency of the Graphene-Silver-TiO2 matrix
    efficiency_factor = 0.65 
    
    # Calculate energy density (Gigawatts per cm2)
    energy_density = laser_power_kw / (spot_size_mm2 * 0.01)
    
    # Thrust generated (in Millinewtons) per pulse
    thrust_mn = (energy_density * pulse_duration_ns) * efficiency_factor
    
    return round(thrust_mn, 4)

# Example: 10kW Laser, 1mm spot size, 10ns pulse
print(f"Propulsion Force: {calculate_ablation_thrust(10, 1, 10)} mN per pulse")
